services:
  # Main API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskgenius-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/tasks.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
      - ALLOWED_ORIGINS=*
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskgenius-frontend
    ports:
      - "3000:3000"
    environment:
      # This should match the name of the API service in docker-compose
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: taskgenius-network
